### ISSUE TITLE
M1 Module 1 META: Mindfully Evolving, Thriving & Advocating - Week 1

### ISSUE THREAD

**Issue by paveljee** [drzhelnov/drzhelnov.github.io#1]
_View these items. Optionally, contribute [glternatives](http://glternative.com) (or request if items unavailable). Check out items when done._

- [x] Foreword IN: Smith's Patient Centered Interviewing
- [x] Ch 1 - The Medical Interview IN: Smith's Patient Centered Interviewing
- [x] Ch 2 - Data-Gathering and Empathy Skills IN: Smith's Patient Centered Interviewing
- [ ] Ch 3 - The Beginning of the Interview: Patient Centered Interviewing IN: Smith's Patient Centered Interviewing
- [ ] Wade DT, Halligan PW. The biopsychosocial model of illness: a model whose time has come. Clin Rehabil. 2017 Aug;31(8):995-1004. doi: 10.1177/0269215517709890.
- [ ] Lines LM, Lepore M, Wiener JM. Patient-centered, Person-centered, and Person-directed Care: They are Not the Same. Med Care. 2015;53(7):561-563. doi:10.1097/MLR.0000000000000387
- [ ] No Apparent Distress by Rachel Pearson
- [ ] A Not Entirely Benign Procedure by Perri Klass
- [ ] Jagosh J, Donald Boudreau J, Steinert Y, Macdonald ME, Ingram L. The importance of physician listening from the patients' perspective: enhancing diagnosis, healing, and the doctor-patient relationship. Patient Educ Couns. 2011;85(3):369-374. doi:10.1016/j.pec.2011.01.028
- [ ] Ch 16 - Musculoskeletal Physical Examination - Bates
- [ ] Ch 16 - 16.1 Introduction - Bates Visual Guide to Physical Examination
- [ ] Ch 16 - 16.2 Anatomy Review - Mandible - Bates Visual Guide to Physical Examination
- [ ] Ch 16 - 16.1 Introduction - Bates Visual Guide to Physical Examination
- [ ] Ch 16 - 16.2 Anatomy Review - Mandible - Bates Visual Guide to Physical Examination
- [ ] Ch 16 - 16.3 Examining the Mandible - Bates Visual Guide to Physical Examination
- [ ] Ch 16 - 16.4 Anatomy Review - Shoulders - Bates Visual Guide to Physical Examination
- [ ] Ch 16 - 16.5 Examining the Shoulders - Bates Visual Guide to Physical Examination
- [ ] Ch 16 - 16.6 Anatomy Review - Elbows - Bates Visual Guide to Physical Examination
- [ ] Ch 16 - 16.7 Examining the Elbows - Bates Visual Guide to Physical Examination
- [ ] Ch 16 - 16.8 Anatomy Review - Wrists and Hands - Bates Visual Guide to Physical Examination
- [ ] Ch 16 - 16.9 Examining the Wrists and Hands - Bates Visual Guide to Physical Examination
- [ ] Ch 16 - 16.10 Anatomy Review - Spine - Bates Visual Guide to Physical Examination
- [ ] Ch 16 - 16.11 Examining the Spine - Bates Visual Guide to Physical Examination
- [ ] Ch 16 - 16.12. Anatomy Review - Hips - Bates Visual Guide to Physical Examination
- [ ] Ch 16 - 16.13 Examining the Hips - Bates Visual Guide to Physical Examination
- [ ] Ch 16 - 16.14 Anatomy Review - Knees - Bates Visual Guide to Physical Examination
- [ ] Ch 16 - 16.15 Examining the Knees - Bates Visual Guide to Physical Examination
- [ ] Ch 16 - 16.17 Examining the Ankles and Feet - Bates Visual Guide to Physical Examination
- [ ] <s>[Careers in Medicine](https://www.aamc.org/cim/)</s> Unavailable, so replacing with The Ultimate Guide To Choosing A Medical Specialty by Brian Freeman, 4th Edition (2018), and
- [ ] _(cont’d)_ How to Choose a Medical Specialty by Anita D. Taylor, 6th Edition (2016)
- [ ] Ch 17 - 17.3 Anatomy Review - Cranial Nerves - Bates Visual Guide to Physical Examination
- [ ] Ch 17 - 17.4 Examining the Cranial Nerves I-XII - Bates Visual Guide to Physical Examination
- [ ] Ch 17 - 17.5 Examining the Motor System - Bates Visual Guide to Physical Examination
- [ ] Ch 17 - 17.6 Assessment of Coordination - Bates Visual Guide to Physical Examination
- [ ] Ch 18 - Nervous System: Sensory System and Reflexes Bates Visual Guide to Physical Examination
- [ ] [Library Lab Outline](https://guides.utmb.edu/ld.php?content_id=55939917)
- [ ] [Evaluating Health Information and Literature Validity](https://guides.utmb.edu/ld.php?content_id=55939861)
- [ ] [Library Lab Exercises](https://utmb.libwizard.com/f/meta-librarylab)
- [ ] #10
